DirectoryPath: public
MaxConcurrent: 4
LogLevel: 2
CheckExternal: false
IgnoreInternalEmptyHash: true
IgnoreMissingTrailingSlash: true
IgnoreDirectoryMissingTrailingSlash: true
IgnoreAltMissing: true
# Added to address site scale and memory growth
IgnoreDirs:
  - docs/archives
ChecksToSkip:
  - MissingAltTag
  - DirectoryIndex
  - AltMissing