FROM rancherlabs/longhorn-website:build
ENV HUGO_ENV dev

VOLUME ["/run/archetypes", "/run/assets", "/run/content", "/run/data", "/run/layouts", "/run/scripts", "/run/static", "/run/themes", "/run/.git"]
WORKDIR /run

# Expose default hugo port
EXPOSE 9002

ENTRYPOINT ["hugo", "serve", "--bind=0.0.0.0", "--buildDrafts", "--buildFuture", "--baseURL=" ]
